language: go

go:
  - "1.15"

services:
  - docker

global:
  - COMPOSE_VERSION=1.25.4

env:
  global:
    - COMPOSE_VERSION=1.25.4
    - GO111MODULE=on
  jobs:
    - TEST_SUITE=tests
    - TEST_SUITE=linters

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script: |
  set -x
  case $TEST_SUITE in
  tests)
      ./run_tests.sh
      ;;
  linters)
      ./.travis/linters.sh
      ;;
  *)
      echo "[!] Unknown test suite: ${TEST_SUITE}. Exiting."
      exit 1
  esac
